version: "3.9"
services:
  react:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - 5173:5173
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/
      && npm run dev"
